spring.application.name=ai-code-review
spring.profiles.active=local
server.port=8080

ai.api.key=AIzaSyAn0rCxaGsI8oC9tcoZskyaHbqqVatAV84
ai.api.url=https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-pro:generateContent