spring.application.name=ai-code-review
spring.profiles.active=local
server.port=8080

ai.api.key=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
ai.api.url=https://api.groq.com/openai/v1/chat/completions