spring.application.name=ai-code-review
spring.profiles.active=local
server.port=8088

groq.api.key=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
groq.api.url=https://api.groq.com/openai/v1/chat/completions

# Persistence Configuration
spring.jpa.hibernate.ddl-auto=validate
spring.flyway.enabled=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Actuator Configuration
management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.endpoint.health.show-details=always
management.info.env.enabled=true

# Swagger/OpenAPI Configuration
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

# OAuth2 Configuration
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=openid,profile,email

spring.security.oauth2.client.registration.github.client-id=${GITHUB_CLIENT_ID}
spring.security.oauth2.client.registration.github.client-secret=${GITHUB_CLIENT_SECRET}
spring.security.oauth2.client.registration.github.scope=read:user,user:email
